version: "3.3"
services:
  notification-service:
    build:
      context: "../../"
      dockerfile: config/docker/Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_started

  redis:
    image: redis
    ports:
    - "6379:6379"
